# 메인 파일 이름을 지정하세요.
main_file = 'main.py'

# 데이타 파일들을 지정하세요.
data_files = [
    'ball21x21.png','character2.jpg','character3.png','field.png','font.png','score.png','soccer_character.png','soccer_character_blue.png','soccer_character_red.png'
]

# 데이타가 들어있는 폴더들을 지정하세요.
data_folders = [
    # fill here
]

